# Generated by Django 4.2.1 on 2023-06-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='discounts',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
